### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wycats** [wycats/wasm#1]
- [ ] Correctly infer number literals
- [ ] Correctly infer all variables
- [ ] Type checking
- [ ] Add type aliases
- [ ] Add Copy structs
- [ ] Add modules
- [ ] Add reference types

Questions

- [ ] What ownership model do we want? (or just GC?)
- [ ] Do we want/need mutable variables?
- [ ] What's the macro story?
- [ ] If we have generics, how do we sidestep Rust's "fork the world" problems?
  - [ ] Send/Sync
  - [ ] Sized
- [ ] Can we make the derive() story nicer out of the box (you have to derive too many things too often in Rust, but the explicitness is nice)
- [ ] Probably no null and no exceptions, so do we need `?`?
- [ ] Can we do [TCP](http://gafter.blogspot.com/2006/08/tennents-correspondence-principle-and.html)?
  - [ ] It's a personal hobby horse, so let's say yes 😉
